IDGS904_tema1/Controllers/TraductorController.cs
using IDGS904_tema1.Models;
using IDGS904_tema1.Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace IDGS904_tema1.Controllers
{
    public class TraductorController : Controller
    {
        // GET: Traductor
        public ActionResult Index()
        {
            return View();
        }

        
        public ActionResult RegistrarTraducc(Traduccion Trad)
        {
            //creamos una variable donde guardas la clase servicio
            var op1 = new GuardarServicesTraductor();
            //llamamos el servicio
            op1.GuardaArchivoTraduc(Trad);

            var arch = new LeerServicesTraductor();
            ViewBag.Archivo = arch.LeerArchivoTraducc();
            return View();
        }

        public ActionResult BuscarTraducc(Traduccion Trad)
        {
            Trad.Resultado = Trad.Radio();
            ViewBag.Resultado = Trad.Resultado;
            return View();

            
        }

    }
    }

IDGS904_tema1/Views/Traductor/BuscarTraducc.cshtml
@model IDGS904_tema1.Models.Traduccion

@{
    ViewBag.Title = "BuscarTraducc";
}

<h2>BuscarTraducc</h2>

@using (Html.BeginForm())
{

    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => Model.Traducir, htmlAttributes:
    new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Traducir, new
           {
               htmlAtributes =
    new { @class = "form-control" }
           })
            </div>
        </div>
    </div>

    <div class="form-group">
        <label class="custom-radio">
            @Html.RadioButtonFor(model => model.Lenguaje, "1")
            <span class="checkmark"></span>
            Español
        </label>
        <br />
        <label class="custom-radio">
            @Html.RadioButtonFor(model => model.Lenguaje, "2")
            <span class="checkmark"></span>
            Ingles
        </label>
    </div>
    
    <h1>Traduccion: @ViewBag.Resultado</h1>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="BuscarTraduccion" class="btn btn-default" />
        </div>
    </div>
    <div class="form-group">
        @Html.ActionLink("Regresar a RegistrarTraducciones", "RegistrarTraducc", "Traductor")
    </div>



}

IDGS904_tema1/Views/Traductor/RegistrarTraducc.cshtml
@model IDGS904_tema1.Models.Traduccion

@{
    ViewBag.Title = "RegistrarTraducc";
}

<h2>RegistrarTraducc</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Traduccion</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Espanol, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Espanol, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Espanol, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ingles, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ingles, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ingles, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

    <div>
        <input type="submit" name="Mostrar" value="Mostrar" class="btn btn-default show-table-btn" />
    </div>

    <div class="form-group">
        @Html.ActionLink("Buscar Traducciones", "BuscarTraducc", "Traductor")
    </div>

    <h4>Mostrar registro de traducciones</h4>
    <style>
        .hidden {
            display: none;
        }
    </style>

    <table class="table table-striped">


        <thead>
        <th>Español</th>
        <th>Ingles</th>

        </thead>
        <tbody>
            @foreach (string tem in ViewBag.Archivo)
            {

                <tr>
                    @foreach (string item in tem.Split(' '))
                    {
                        <td>@item</td>
                    }
                </tr>

            }
        </tbody>
    </table>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var mostratabla = document.querySelector('.show-table-btn');
            var tabla = document.querySelector('.table-striped');
            tabla.classList.add('hidden');

            mostratabla.addEventListener('click', function () {
                tabla.classList.remove('hidden');
            });
        });

    </script>